protected/controllers/StatusController.php
<?php

class StatusController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/column2';

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
			'postOnly + delete', // we only allow deletion via POST request
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('allow',  // allow all users to perform 'index' and 'view' actions
				'actions'=>array('index','view'),
				'users'=>array('*'),
			),
			array('allow', // allow authenticated user to perform 'create' and 'update' actions
				'actions'=>array('create','update','delete'),
				'users'=>array('@'),
			),
			// array('allow', // allow admin user to perform 'admin' and 'delete' actions
			// 	'actions'=>array('admin','delete'),
			// 	'users'=>array('admin'),
			// ),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id)
	{
		$this->render('view',array(
			'model'=>$this->loadModel($id),
		));
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
		$model=new Status;

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Status']))
		{
			$model->attributes=$_POST['Status'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->id));
		}

		$this->render('create',array(
			'model'=>$model,
		));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		$model=$this->loadModel($id);

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Status']))
		{
			$model->attributes=$_POST['Status'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->id));
		}

		$this->render('update',array(
			'model'=>$model,
		));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		$this->loadModel($id)->delete();

		// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
		if(!isset($_GET['ajax']))
			// $this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin')); 
			// The above particular redirection always screws it up. So changing it to what I need.
			$this->redirect(Yii::app()->request->UrlReferrer);
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
		$dataProvider=new CActiveDataProvider('Status');
		$this->render('index',array(
			'dataProvider'=>$dataProvider,
		));
	}

	/**
	 * Manages all models.
	 */
	public function actionAdmin()
	{
		$model=new Status('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['Status']))
			$model->attributes=$_GET['Status'];

		$this->render('admin',array(
			'model'=>$model,
		));
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer $id the ID of the model to be loaded
	 * @return Status the loaded model
	 * @throws CHttpException
	 */
	public function loadModel($id)
	{
		$model=Status::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param Status $model the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='status-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
}

protected/controllers/UserController.php
<?php

class UserController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/column1';

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
			'postOnly + delete', // we only allow deletion via POST request
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('allow',  // allow all users to perform 'index' and 'view' actions
				'actions'=>array('view'),
				'users'=>array('*'),
			),
			array('allow', // allow authenticated user to perform 'create' and 'update' actions
				'actions'=>array('create','update','index'),
				'users'=>array('@'),
			),
			array('allow', // allow admin user to perform 'admin' and 'delete' actions
				'actions'=>array('admin','delete'),
				'users'=>array('admin'),
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id)
	{
		$this->render('view',array(
			'model'=>$this->loadModel($id),
		));
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
		$model=new User;

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['User']))
		{
			$model->attributes=$_POST['User'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->id));
		}

		$this->render('create',array(
			'model'=>$model,
		));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		$model=$this->loadModel($id);

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['User']))
		{
			$model->attributes=$_POST['User'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->id));
		}

		$this->render('update',array(
			'model'=>$model,
		));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		$this->loadModel($id)->delete();

		// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
		if(!isset($_GET['ajax']))
			$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
	}

	/**
	 * This is the main page where all the spice happens.
	 */
	public function actionIndex()
	{
		$this->pageTitle = 'Welcome '.ucfirst(Yii::app()->user->name);

		$statusLast = new Status;


		$user = User::model()->findByPk(Yii::app()->user->id); // This would only get the specific user
		$status = $this->createStatus();
		$money = $this->createMoney();
		//$dataProvider=new CActiveDataProvider('User');  // As this is not actuallly required.
		$this->render('index',array(
			//'dataProvider'=>$dataProvider,
			'status' => $status, // sending the variable to the view file.
			'model' => $user,
			'statuses' => $user->status, // This is using Relational AR
			'lastStatus' => $statusLast->getLastStatus(), // This would get the last status for the Last Status
			'money' => $money,

		));
	}

	public function createStatus(){
		$status = new Status; // This would create a new instance of the status.
		if(isset($_POST['Status'])){
			$status->attributes = $_POST['Status']; // This would give a massive assign
			if($status->validate()){
			$status->save();
			Yii::app()->user->setFlash('statusCreated','Your status has been submitted.');
			$this->refresh(); 
			}
		}

		return $status;
	}

	public function createMoney(){
		$money = new Money;
		if(isset($_POST['Money'])){
			$money->attributes = $_POST['Money']; // Massive assignment
			if($money->validate()){
				$money->save();
				Yii::app()->user->setFlash('moneyCreated','Your amount has been added. Please note that the moderator can edit or remove it.');
				$this->refresh();
			}
		}

		return $money;
	}


	/**
	* Handles resource upload
	* @throws CHttpException
	*/
	public function actionUpload()
	{
    header('Vary: Accept');
    if (isset($_SERVER['HTTP_ACCEPT']) && 
        (strpos($_SERVER['HTTP_ACCEPT'], 'application/json') !== false))
    {
        header('Content-type: application/json');
    } else {
        header('Content-type: text/plain');
    }
    $data = array();
 
    $model = new User('upload');
    $model->picture = CUploadedFile::getInstance($model, 'picture');
    if ($model->picture !== null  && $model->validate(array('picture')))
    {
        $model->picture->saveAs(
        Yii::getPathOfAlias('application.uploads').'/'.$model->picture->name);
        $model->file_name = $model->picture->name;
        // save picture name
        if( $model->save())
        {
            // return data to the fileuploader
            $data[] = array(
                'name' => $model->picture->name,
                'type' => $model->picture->type,
                'size' => $model->picture->size,
                // we need to return the place where our image has been saved
                //'url' => $model->getImageUrl(), // Should we add a helper method?
                // we need to provide a thumbnail url to display on the list
                // after upload. Again, the helper method now getting thumbnail.
                //'thumbnail_url' => $model->getImageUrl(User::IMG_THUMBNAIL),
                // we need to include the action that is going to delete the picture
                // if we want to after loading 
                'delete_url' => $this->createUrl('my/delete', 
                    array('id' => $model->id, 'method' => 'uploader')),
                'delete_type' => 'POST');
        } else {
            $data[] = array('error' => 'Unable to save model after saving picture');
        }
    } else {
        if ($model->hasErrors('picture'))
        {
            $data[] = array('error', $model->getErrors('picture'));
        } else {
            throw new CHttpException(500, "Could not upload file ".     CHtml::errorSummary($model));
        }
    }
    // JQuery File Upload expects JSON data
    echo json_encode($data);
}
 

	/**
	 * Manages all models.
	 */
	public function actionAdmin()
	{
		$model=new User('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['User']))
			$model->attributes=$_GET['User'];

		$this->render('admin',array(
			'model'=>$model,
		));
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer $id the ID of the model to be loaded
	 * @return User the loaded model
	 * @throws CHttpException
	 */
	public function loadModel($id)
	{
		$model=User::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param User $model the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='user-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
}

protected/views/user/_form.php
<?php
/* @var $this UserController */
/* @var $model User */
/* @var $form CActiveForm */
?>

<div class="form">

<?php $form=$this->beginWidget('bootstrap.widgets.TbActiveForm', array(
	'id'=>'user-form',
	'enableAjaxValidation'=>false,
)); ?>

	<p class="note">Fields with <span class="required">*</span> are required.</p>

	<?php echo $form->errorSummary($model); ?>

	
		<?php echo $form->labelEx($model,'name'); ?>
		<?php echo $form->textField($model,'name',array('size'=>45,'maxlength'=>45)); ?>
		<?php echo $form->error($model,'name'); ?>
	

	
		<?php echo $form->labelEx($model,'lastname'); ?>
		<?php echo $form->textField($model,'lastname',array('size'=>45,'maxlength'=>45)); ?>
		<?php echo $form->error($model,'lastname'); ?>
	

	
		<?php echo $form->labelEx($model,'course'); ?>
		<?php echo $form->textField($model,'course',array('size'=>45,'maxlength'=>45)); ?>
		<?php echo $form->error($model,'course'); ?>
	


		<?php echo $form->labelEx($model,'email'); ?>
		<?php echo $form->textField($model,'email',array('size'=>60,'maxlength'=>100)); ?>
		<?php echo $form->error($model,'email'); ?>
	
	
		<?php echo $form->labelEx($model,'username'); ?>
		<?php echo $form->textField($model,'username',array('size'=>45,'maxlength'=>45)); ?>
		<?php echo $form->error($model,'username'); ?>
	

	
		<?php echo $form->labelEx($model,'password'); ?>
		<?php echo $form->passwordField($model,'password',array('size'=>45,'maxlength'=>45)); ?>
		<?php echo $form->error($model,'password'); ?>
		

		<?php echo $form->labelEx($model,'password_repeat'); ?>
		<?php echo $form->passwordField($model,'password_repeat',array('size'=>45,'maxlength'=>45)); ?>
		<?php echo $form->error($model,'password_repeat'); ?>
	

	
		<?php echo $form->labelEx($model,'about'); ?>
		<?php echo $form->textArea($model,'about',array('rows'=>6, 'cols'=>50)); ?>
		<?php echo $form->error($model,'about'); ?>
	

	
		<?php echo $form->labelEx($model,'sec_ques'); ?>
		<?php echo $form->textField($model,'sec_ques',array('size'=>45,'maxlength'=>45)); ?>
		<?php echo $form->error($model,'sec_ques'); ?>
	

	
		<?php echo $form->labelEx($model,'answer'); ?>
		<?php echo $form->textField($model,'answer',array('size'=>45,'maxlength'=>45)); ?>
		<?php echo $form->error($model,'answer'); ?>
	

	
	

	<div class="row buttons">
		<?php echo CHtml::submitButton($model->isNewRecord ? 'Create' : 'Save'); ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- form -->

protected/views/user/_search.php
<?php
/* @var $this UserController */
/* @var $model User */
/* @var $form CActiveForm */
?>

<div class="wide form">

<?php $form=$this->beginWidget('CActiveForm', array(
	'action'=>Yii::app()->createUrl($this->route),
	'method'=>'get',
)); ?>

	<div class="row">
		<?php echo $form->label($model,'id'); ?>
		<?php echo $form->textField($model,'id',array('size'=>10,'maxlength'=>10)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'name'); ?>
		<?php echo $form->textField($model,'name',array('size'=>45,'maxlength'=>45)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'lastname'); ?>
		<?php echo $form->textField($model,'lastname',array('size'=>45,'maxlength'=>45)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'username'); ?>
		<?php echo $form->textField($model,'username',array('size'=>45,'maxlength'=>45)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'about'); ?>
		<?php echo $form->textArea($model,'about',array('rows'=>6, 'cols'=>50)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'created_on'); ?>
		<?php echo $form->textField($model,'created_on'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'updated_on'); ?>
		<?php echo $form->textField($model,'updated_on'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'ip'); ?>
		<?php echo $form->textField($model,'ip',array('size'=>45,'maxlength'=>45)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'active'); ?>
		<?php echo $form->textField($model,'active'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'power'); ?>
		<?php echo $form->textField($model,'power'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'ban'); ?>
		<?php echo $form->textField($model,'ban'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'sec_ques'); ?>
		<?php echo $form->textField($model,'sec_ques',array('size'=>45,'maxlength'=>45)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'answer'); ?>
		<?php echo $form->textField($model,'answer',array('size'=>45,'maxlength'=>45)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'course'); ?>
		<?php echo $form->textField($model,'course',array('size'=>45,'maxlength'=>45)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'profilepic'); ?>
		<?php echo $form->textField($model,'profilepic',array('size'=>60,'maxlength'=>255)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'thumbnail'); ?>
		<?php echo $form->textField($model,'thumbnail',array('size'=>60,'maxlength'=>255)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'email'); ?>
		<?php echo $form->textField($model,'email',array('size'=>60,'maxlength'=>100)); ?>
	</div>

	<div class="row buttons">
		<?php echo CHtml::submitButton('Search'); ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- search-form -->

protected/views/user/create.php
<?php
/* @var $this UserController */
/* @var $model User */

$this->breadcrumbs=array(
	'Users'=>array('index'),
	'Create',
);

$this->menu=array(
	array('label'=>'List User', 'url'=>array('index')),
	array('label'=>'Manage User', 'url'=>array('admin')),
);
?>

<h1>Create User</h1>

<?php echo $this->renderPartial('_form', array('model'=>$model)); ?>

protected/views/user/index.php
<?php
/* @var $this UserController */
/* @var $dataProvider CActiveDataProvider */

?>



<div class="span10">
	<div class="row-fluid">
		<div class="span3">
			<img <?php echo "src=".Yii::app()->request->baseUrl."/uploads/san.png"; ?> <?php echo CHtml::encode("alt="."\"".$model['name']."\""); ?> class="img-rounded img-polaroid">
	 					<?php 
							$this->widget('bootstrap.widgets.TbButton',array(
								'htmlOptions' => array('style'=>'margin-top: 5px;','class'=>'span12'),
								'label' => 'Change Profile Pic',
								'type' =>'warning',
								'block' => true,
						)); ?>

	 		<div class="row-fluid">
	 			<div class="span12">
	 				<p class="lead" style="text-align:center; margin-top: 10px;">MY TO-DO LIST</p>
        	

          <?php 
          $this->widget('bootstrap.widgets.TbTabs', array(
				'type'=>'tabs',
				'htmlOptions' => array('class'=>'bday-wrap'),
				'stacked'=>true,
				'tabs'=>array(
								array('label'=>'Submit Brake Report'),
								array('label'=>'Submit Tyres Pic'),
								array('label'=>'Repair Body'),
								array('label'=>'Paint Hood'),
								array('label'=>'Test Driving'),
								
					),
			)); ?>

			<?php 
			$this->widget('bootstrap.widgets.TbButton',array(
								'htmlOptions' => array('style'=>'margin-top: -25px;'),
								'label' => 'Show all',
								'type' =>'info',
								'size' => 'mini'
			)); ?>


        
	 			</div>
	 		</div>
		</div>
		
		<div class="span9">
	 				<div class="well">
	 					<div class="row-fluid">
	 						<div class="span6">
	 							<h1 style="color: #99253b;"><?php echo CHtml::encode($model['name']." ".$model['lastname']); ?></h1>
	 					<p class="lead"><?php echo CHtml::encode($model['course']); ?></p>
	 					<h2 style="margin-top: -25px;">About me :</h2>
	 					<p><?php CHtml::encode($model['about']); ?></p>
	 					<br>
	 					<address style="margin-top: -15px;">
	 						<abbr title="Phone">P:</abbr> (123) 456-7890 <br>
	 						<abbr title="Email">@:</abbr> <em><?php echo CHtml::encode($model['email']); ?></em>
	 					</address>
	 					<div id="roles">
	 					<span class="label label-important">Admin</span>
	 					<span class="label label-warning">Moderator</span>
	 					<span class="label label-info">Member</span>
	 					</div>
	 					<p style="padding-top:10px;"><strong>Working For Modules :</strong></p>
	 					<span class="badge badge-success">Steering</span>
	 					<span class="badge badge-success">Wheels</span>
	 					<span class="badge badge-success">Hydralics</span>
	 					<span class="badge badge-success">Brakes</span>
	 					<span class="badge badge-success">Body</span>
	 					<span class="badge badge-success">Design</span>
	 					<span class="badge badge-success">Tyres</span>

	 					
	 					<?php $this->renderPartial('/status/_form',array('model'=>$status)); ?>
	 					<?php if (Yii::app()->user->hasFlash('statusCreated')): ?>
	 						<?php 

	 						$this->widget('bootstrap.widgets.TbAlert', array(
	 											
 												'block'=>true, // display a larger alert block?
												'fade'=>true, // use transitions?
												//'closeText'=>'×', // close link text - if set to false, no close link is displayed
												'alerts'=>array( // configurations per alert type
												'statusCreated'=>array(
														'block'=>true, 
														'fade'=>true, 
														'closeText'=>'×',
														), // success, info, warning, error or danger
												),
										)); ?>
	 					<?php endif ?>
						
	 						</div>

	 						<div class="span6">
	 							<!-- This is the area for the graph -->
								<p class="lead" style="margin-left: 35px;">TEAM PROGRESS :</p>

						<?php 
        $this->widget(
            'ext.chartjs.widgets.ChPolar', 
            array(
                'width' => 250,
                'height' => 250,
                'htmlOptions' => array(),
                'drawLabels' => true,
                'datasets' => array(
                    array(
                        "value" => 50,
                        "color" => "rgba(220,30, 70,1)",
                        "label" => "Tyres"
                    ),
                    array(
                        "value" => 25,
                        "color" => "rgba(66,66,66,1)",
                        "label" => "Brakes"
                    ),
                    array(
                        "value" => 40,
                        "color" => "rgba(100,100,220,1)",
                        "label" => "Design"
                    ),
                    array(
                        "value" => 15,
                        "color" => "rgba(20,120,120,1)",
                        "label" => "Hydraulics"
                    )
                ),
                'options' => array()
            )
        ); 
    ?>		
					

	 						</div>
	 					</div>
						<h3>Current Status :</h3>
						<blockquote>
							<p><?php echo CHtml::encode($lastStatus['status']); ?></p>
							 <small><?php echo CHtml::encode($lastStatus['created_on']); ?></small>
						</blockquote>

	 				</div>

	 	</div>

	 	<div class="row-fluid">
	 					<div class="span12">
	 						<div class="well">
							


	 							<?php foreach ($statuses as $status): ?>
	 								<blockquote>
	 								<h4>
	 									<img src="http://placehold.it/64x64">
	 									 <?php echo CHtml::encode($status->user->name); ?>
	 								</h4>

	 								<?php if ($status->user->id === Yii::app()->user->id): ?>
	 									<?php echo CHtml::link('<i class="icon-remove-sign icon-large"></i>','#',array('submit'=>array('status/delete','id'=>$status->id),'confirm'=>'Are you sure?','class'=>'pull-right', 'style'=>'text-decoration:none;'));  ?>
	 								<?php endif ?>

	 								<p>
	 									<?php echo CHtml::encode($status->status); ?>
	 								</p>
	 								 <small><?php echo CHtml::encode($status->created_on); ?></small>
	 							</blockquote>
	 							<?php endforeach ?>

	 							 <div class="row-fluid">
                    <div class="span11 offset1 well" style="margin-top:10px;"> <span class="label label-important">COMMENTS :</span> 
                    
                    <!-- First Comment-->
                    
                    <div class="comment-wrap">
                        <blockquote><!--<img src="https://graph.facebook.com/sankalpsingha/picture" class="pull-left">-->
                        <h4>Sankalp Singha</h4>
                        <small>31 Apr @ 2.55 PM </small>
                        <p>This is a very good theory...</p>
                      </blockquote>
                       
                        <!--Next Dummy comment -->
                        
                       
                         </div>
                  </div>
                  </div>
	 							<input  class="span12" placeholder="Enter your comment here..."></input>
    						<button class="btn btn-mini btn-success" type="button" style="margin-top: 10px;"><i class="icon-comment"></i> Post Comment</button>
	 						</div>
	 					</div>
	 				</div>
	 		</div>



	</div>
</div>

<div class="span2">
	<div class="well ">

			<p style=" text-align: center;"><strong>Amount Spent :</strong></p>
			<p class="lead" style="text-align: center;">2789/-</p>

			<?php 

				$this->widget('bootstrap.widgets.TbButtonGroup', array(
						'type' => 'primary', // '', 'primary', 'info', 'success', 'warning', 'danger' or 'inverse'
						'size' => 'mini',
						'buttons' => array(
											array('label' => 'Action', 'url' => '#'), // this makes it split :)
											array('items' => array(
											array('label' => 'Action', 'url' => '#'),
											array('label' => 'Another action', 'url' => '#'),
											array('label' => 'Something else', 'url' => '#'),
											'---',
											array('label' => 'Separate link', 'url' => '#'),
											)),
										),
									));
				 ?>

			<?php $this->widget('bootstrap.widgets.TbButton',array(
				'label' => 'Add',
				'icon' => 'icon-beer',
				'type' => 'success',
				'size' => 'mini',
				'htmlOptions' => array(
					'data-toggle' => 'modal',
					'data-target' => '#myModal',
					),
				)); ?>


				<?php $this->beginWidget('bootstrap.widgets.TbModal', array('id' => 'myModal')); ?>
 
					<div class="modal-header">
					<a class="close" data-dismiss="modal">&times;</a>
					<h4>Modal header</h4>
					</div>
 
					<div class="modal-body">
					<?php $this->renderPartial('/money/_form',array('model'=>$money)); ?>
					</div>
 
					<div class="modal-footer">
					<?php $this->widget('bootstrap.widgets.TbButton', array(
					'type' => 'primary',
					'label' => 'Save changes',
					'url' => '#',
					'htmlOptions' => array('data-dismiss' => 'modal'),
					)); ?>
					<?php $this->widget('bootstrap.widgets.TbButton', array(
					'label' => 'Close',
					'url' => '#',
					'htmlOptions' => array('data-dismiss' => 'modal'),
					)); ?>
					
					</div>
 
<?php $this->endWidget(); ?>



		</div>
</div>